// Public type entry point for `@tightknitai/slack-block-kit-validator/types`.
// Re-exports the user-facing types generated from src/slack-block-kit.schema.json.
// Intermediate `*1`/`*2` artifacts that json-schema-to-typescript emits while
// flattening `allOf` are deliberately not re-exported.

export type {
  // Scalars
  ActionId,
  ActionsBlock,
  // Per-container element unions
  ActionsBlockElement,
  AlertBlock,
  // Blocks (discriminated union + each member)
  Block,
  BlockId,
  // Block elements
  ButtonElement,
  CardBlock,
  CarouselBlock,
  ChannelsSelectElement,
  CheckboxesElement,
  // Composition objects
  ConfirmObject,
  ContextActionsBlock,
  ContextActionsBlockElement,
  ContextBlock,
  ContextBlockElement,
  ConversationFilterObject,
  ConversationsSelectElement,
  DatepickerElement,
  DatetimepickerElement,
  DispatchActionConfigObject,
  DividerBlock,
  EmailInputElement,
  ExternalSelectElement,
  // Table / task card subobjects
  FeedbackButtonSubobject,
  FeedbackButtonsElement,
  FileBlock,
  FileInputElement,
  HeaderBlock,
  // View surfaces
  HomeView,
  IconButtonElement,
  ImageBlock,
  ImageElement,
  InputBlock,
  InputBlockElement,
  MarkdownBlock,
  ModalView,
  MrkdwnTextObject,
  MultiChannelsSelectElement,
  MultiConversationsSelectElement,
  MultiExternalSelectElement,
  MultiStaticSelectElement,
  MultiUsersSelectElement,
  NumberInputElement,
  OptionGroupObject,
  OptionObjectOverflow,
  OptionObjectPlainText,
  OptionObjectRadioOrCheckbox,
  OverflowElement,
  PlaceholderObject,
  PlainTextInputElement,
  PlainTextObject,
  PlanBlock,
  RadioButtonsElement,
  RichTextBlock,
  // Rich text
  RichTextBroadcastLeaf,
  RichTextChannelLeaf,
  RichTextColorLeaf,
  RichTextContainerElement,
  RichTextDateLeaf,
  RichTextEmojiLeaf,
  RichTextInputElement,
  RichTextLeaf,
  RichTextLinkLeaf,
  RichTextListElement,
  RichTextPreformattedElement,
  RichTextQuoteElement,
  RichTextSectionElement,
  RichTextStyleObject,
  RichTextTeamLeaf,
  RichTextTextLeaf,
  RichTextUsergroupLeaf,
  RichTextUserLeaf,
  SectionAccessoryElement,
  SectionBlock,
  // Top-level payload shapes
  SlackBlockKitPayload,
  SlackFileObject,
  StaticSelectElement,
  TableBlock,
  TableCell,
  TableColumnSetting,
  TaskCardBlock,
  TaskCardInlineObject,
  TextObject,
  TimepickerElement,
  TriggerObject,
  UrlInputElement,
  UrlSourceElement,
  UsersSelectElement,
  VideoBlock,
  WorkflowButtonElement,
  WorkflowObject,
} from "./types.generated.js";
